# todo pull api-specs

stages:
  - build
  - package

build_openapi:
  stage: build
  image: openapitools/openapi-generator-cli
  script:
    - ./build.sh
  cache:
    key: build-cache
    paths:
      - out/

package_python:
  stage: package
  image: python:3.8
  script:
    - cd out/ && python setup.py sdist
  cache:
    key: build-cache
    paths:
      - out/
  artifacts:
    name: cvg-python-sdk-${CI_COMMIT_SHA}.tar.gz
    paths:
      - out/dist/cvg-python-sdk-1.0.0.tar.gz
    expire_in: 1 days
