openapi: 3.0.0

info:
  title: 'Custom Headers'
  version: '{{VERSION}}'

paths: {}

components:
  schemas:
    CustomSipHeaders:
      type: object
      example:
        "X-CustomHeader":
          - "some-value"
        "X-ASecondCustomHeader":
          - "more values"
          - "even more values"
      description: |-
        This object has a property for each custom SIP header. A header is considerd a custom header if its name
        starts with `X-`, no other header names are allowed. Header names are case-insensitive and thus unique in
        this object. Each header has a list of header values as its value. The order of the header values per header
        is consistent with the order in which the headers appeared in the SIP message.

        **Notes**:
         * All header names will have their letter casing converted to lowercase.
         * The amount of data that can be transferred via SIP headers is *very* limited. Only 128 bytes of data will be
           accepted.
         * Custom SIP headers are a best-effort API, any SIP proxy on the path to the system, that is supposed to read
           the information, can manipulate or drop headers.
      additionalProperties:
        type: array
        items:
          type: string
        description: The values of the header in order the they appeared in the SIP message.
    CustomDialogData:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
      example:
        CustomKey:
          - "some value"
        ASecondCustomKey:
          - "more values"
          - "even more values"
      description: |
        Contains custom data that was attached to the dialog via the Dialog API before the session request.
        This is only possible when using the Provisioning API, otherwise the map is always empty.
