openapi: 3.0.0

info:
  title: 'Custom Headers'
  version: '{{VERSION}}'

paths: {}

components:
  schemas:
    GoogleServiceAccount:
      description: A google service account as JSON
    GoogleInsightsServiceAccount:
      allOf:
        - $ref: '#/components/schemas/GoogleServiceAccount'
        - description: A service account with privileges to access Google Insights and Google Cloud Storage
