openapi: 3.0.0

info:
  title: 'Project Health'
  version: '{{VERSION}}'

paths: {}

components:
  schemas:
    HealthStatus:
      type: string
      enum:
        - UNKNOWN
        - OK
        - WARNING
        - CRITICAL
      description: |-
        Overall health status for a project, determined by the health event with the worst status.
        `UNKNOWN` if no calls happened within the checked time period.
