openapi: 3.0.0

info:
  title: 'Project types'
  version: '{{VERSION}}'

paths: {}

components:
  schemas:
    BotUrl:
      type: string
      description: URL to the server that implements the Bot API.
      example: http://echo-rest-bot:9090
    BotToken:
      type: string
      description: A bearer token that is used for calls to the Bot API.
    BotConfiguration:
      description: |-
        Advanced configuration for the bot. Can contain arbitrary JSON data, including `null`.
        Please consult the documentation of the bot you are using for the required format.
    InactivityTimeout:
      type: integer
      description: |-
        Duration after which the inactivity detection timeout occurs.
        The value is in milliseconds.
      example: 15000
      minimum: 2000
      maximum: 20000
    MinimumNoiseLevel:
      type: integer
      description: |-
        Optional transcription parameter. A level in dB that a signal must
        surpass to be considered at all.
      example: -45
      minimum: -60
      maximum: -30
    UtteranceTimeout:
      type: integer
      example: 500
      minimum: 200
      maximum: 1000
      description: |-
        Optional transcription parameter. The time (milliseconds) of silence
        that must occur after non-noise to complete an utterance.
    Callback:
      type: string
      format: uri
      description: |-
        The base URL against which API calls should be made, e.g. https://cognitivevoice.io/v1 for the
        production environment and https://stage.cognitivevoice.io/v1 for the staging environment.
