openapi: 3.0.0

info:
  title: 'Recording'
  version: '{{VERSION}}'

paths: {}

components:
  schemas:
    DialogPhase:
      type: string
      default: BOT
      enum:
        - BOT
        - ASSIST
    RecordingId:
      type: string
      format: recording-id
      minLength: 1
      maxLength: 50
      description: |-
        Recording IDs are arbitrary strings which can by supplied to start a dedicated recording in addition to
        the main recording. The ID must be unique within each dialog phase.

        If the recording ID is omitted, `"default"` is used.
    RecordingStartParameters:
      type: object
      required:
        - dialogId
      properties:
        dialogId:
          $ref: 'tokens.yml#/components/schemas/DialogId'
        maxDuration:
          $ref: 'time.yml#/components/schemas/Duration'
          description: |-
            If set, the recording is automatically terminated after the specified duration.

            When a recording is terminated, it will be processed as soon as possible and can't be resumed.
        recordingId:
          $ref: '#/components/schemas/RecordingId'
        speakers:
          type: array
          default: [CUSTOMER, AGENT]
          items:
            $ref: 'speaker.yml#/components/schemas/Speaker'
          minItems: 1
          uniqueItems: true
          description: Which speaker(s) to record, by default both.
    RecordingStopParameters:
      type: object
      required:
        - dialogId
      properties:
        dialogId:
          $ref: 'tokens.yml#/components/schemas/DialogId'
        recordingId:
          $ref: '#/components/schemas/RecordingId'
        terminate:
          type: boolean
          default: false
          description: |-
            Whether the recording should be terminated, rather than just paused. If terminated, the recording will be
            processed as soon as possible instead of deferring processing until the dialog has ended.

            A terminated recording can't be resumed again with `/recording/start`.
