openapi: 3.0.0

info:
  title: 'Speaker'
  version: '{{VERSION}}'

paths: {}

components:
  schemas:
    Speaker:
      type: string
      enum:
        - CUSTOMER
        - AGENT
      description: |-
        The speaker describes a participant of the dialog.

        - `CUSTOMER` is the human caller/callee
        - `AGENT` can be a virtual agent (bot), or a human agent during the assist use case
