openapi: 3.0.0

info:
  title: 'Speech service related objects'
  version: '{{VERSION}}'

paths: {}

components:
  schemas:
    TranscriberSelection:
      type: array
      description: |-
        This parameter is optional. If specified, it overrides the transcriber list from the project settings.

        A list of transcriber vendor names like `"GOOGLE"`. When using custom transcriber profiles,
        the profile name is attached as a suffix separated by a dash, e.g. `"GOOGLE-profile"`.
        Alternatively, the profile token can be used directly (without the vendor name).

        The first transcriber in the list has the highest priority. Additional transcribers
        are used as a fallback (in order) in case a service is currently unreachable.

        The following transcriber vendors are currently available:

          - `GOOGLE`
          - `MICROSOFT`
      items:
        type: string
      minItems: 1

    SynthesizerSelection:
      type: array
      description: |-
        This parameter is optional. If specified, it overrides the synthesizer list from the project settings.

        A list of synthesizer vendor names like `"GOOGLE"`. When using custom synthesizer profiles,
        the profile name is attached as a suffix separated by a dash, e.g. `"GOOGLE-profile"`.
        Alternatively, the profile token can be used directly (without the vendor name).

        The first synthesizer in the list has the highest priority. Additional synthesizers
        are used as a fallback (in order) in case a service is currently unreachable.

        The following synthesizer vendors are currently available:

          - `GOOGLE`
          - `AMAZON`
          - `NUANCE`
          - `MICROSOFT`
          - `IBM`
      items:
        type: string
      minItems: 1

    Vendor:
      type: string
      format: speech-service
      description: A synthesizer / transcriber vendor name
      example: GOOGLE
