name: Python Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Distributions
        run: |
          ./build.sh
      - name: Deploy the Package
        env:
          TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
        run: |
          apt-get install twine
          commit="$(git rev-parse HEAD)"
          twine upload --username __token__ --non-interactive --comment "Built from commit $commit" out/dist/cvg*
